<?php
/**
 * @file
 * Simplenews user list, edit form for adding simplenews category
 *
 * @ingroup simplenews userlist
 */

/**
 * Implements hook_permission
 */
function simplenews_user_list_permission() {
	return array(
			'kabootr_recipient_list' => array(
					'title' => t('Create Kabootr Recipient List'),
			),
	);
}

/**
 * Implements hook_form_alter.
 */
function simplenews_user_list_form_alter(&$form, &$form_state, $form_id) {
	// Add users filters in creation of Newsletter category
	// Role to grant the permissions to
	
  if ($form_id == 'simplenews_admin_category_form' && user_access('kabootr_recipient_list')) {
    include 'includes/simplenews_user_list.admin.inc';
    $form['user_filter'] = array(
        '#type' => 'fieldset',
        '#title' => t('Create Subscription List'),
        '#collapsible' => FALSE
    );
    
    // This tid repersent the term in Newsletter category vocab,
    // In editing newsletter category, tid repersent the Newsletter Category
    $newsletter_tid = NULL;
    if (isset($form['tid']['#value'])) {
      $newsletter_tid = $form['tid']['#value'];
    }
    // Create user filter based on User account field
    // The id's of form user filter has been set to it's user field ID.
    $master_newsletter_tid = variable_get('master_simplenews_category', '');
    if ($newsletter_tid != $master_newsletter_tid) {
      
      $users_filters = simplenews_user_list_create_user_filters($newsletter_tid);
      if ($users_filters != NULL) {
        foreach ($users_filters as $f_key => $f_value) {
          $form['user_filter']['kabootr_user_filter_' . $f_key] = $f_value;
        }
        // Create user list based on selected user filters
        $form['#submit'][] = 'simplenews_user_list_admin_category_form_submit';
      }
    }
    else {
      $message = t("@newsletter is master Category. so no change in subscription list", array(
          '@newsletter' => taxonomy_term_load($master_newsletter_tid)->name
      ));
      drupal_set_message($message, 'warning');
    }
  }
}
