<?php 
/**
 * Exception via amazon request
 */
define('KABOOTR_AMAZON_REQUEST_EXCEPTION', -1);
define('KABOOTR_AMAZON_REQUEST_FAILURE', 0);
define('KABOOTR_AMAZON_REQUEST_SUCCESS', 1);
/**
 * GetIdentityVerificationAttributes Results
 */
define('KABOOTR_IDENTITY_VERIFICATION_NOT', 0);
define('KABOOTR_IDENTITY_VERIFICATION_SUCCESS', 1);
define('KABOOTR_IDENTITY_VERIFICATION_PENDING', 2);

/**
 * SendMail Status
 */
define('KABOOTR_MAIL_NOT_SENT', 0);
define('KABOOTR_MAIL_PENDING', 1);
define('KABOOTR_MAIL_SENT', 2);

/**
 * VerifyEmailIdentity Results
 */
define('KABOOTR_VERIFY_EMAIL_SUCCESS', 1);
define('KABOOTR_VERIFY_EMAIL_ERROR', 0);

/**
 * VerifyDomainIdentity Results
 */
define('KABOOTR_VERIFY_DOMAIN_SUCCESS', 2);
define('KABOOTR_VERIFY_DOMAIN_ERROR', 3);

/**
 * DeleteIdentity Results
 */
define('KABOOTR_DELETE_IDENTITY_ERROR', 0);
define('KABOOTR_DELETE_IDENTITY_SUCCESS', 1);

/**
 * Implements hook_permission
 */
function simplenews_amazon_ses_permission() {
  return array(
      'amazon_ses_configuration' => array(
          'title' => t('Administer Amazon Simple Email Service'),
      ),
  );
}

/**
 * Implements hook_menu
 */
function simplenews_amazon_ses_menu() {
  $items['admin/config/services/amazon_ses/amazon_identity_verify'] = array(
      'title' => 'Verify Sender Identity',
      'type' => MENU_NORMAL_ITEM,
      'access arguments' => array('amazon_ses_configuration'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('amazon_identity_verify_form'),
      'file' => 'includes/simplenews_amazon_ses.admin.inc',
  );
  $items['admin/config/services/amazon_ses/amazon_get_mail_statistics'] = array(
      'title' => 'EMail Statistics',
      'type' => MENU_NORMAL_ITEM,
      'access arguments' => array('amazon_ses_configuration'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('amazon_get_mail_statistics_form'),
      'file' => 'includes/simplenews_amazon_ses.admin.inc',
  );
  $items['admin/config/services/amazon_ses/amazon_identity_list'] = array(
      'title' => 'Idenitity List',
      'type' => MENU_NORMAL_ITEM,
      'access arguments' => array('amazon_ses_configuration'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('amazon_identity_list_form'),
      'file' => 'includes/simplenews_amazon_ses.admin.inc',
  );
  /* $items['admin/config/services/amazon_ses/set_identity_notification_topic'] = array(
      'title' => 'Set Identity Notification Topic',
      'type' => MENU_LOCAL_TASK,
      //'access arguments' => array('amazon_ses_configuration'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('amazon_set_identity_notification_topic_form'),
      'file' => 'includes/simplenews_amazon_ses.admin.inc',
  ); */
  
  $items['admin/config/services/amazon_ses/amazon_domain_dkim_setting'] = array(
      'title' => 'DKIM Setting',
      'type' => MENU_LOCAL_TASK,
      'access arguments' => array('amazon_ses_configuration'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('amazon_domain_dkim_enable_form'),
      'file' => 'includes/simplenews_amazon_ses.admin.inc',
  );
  return $items;
}

/**
 * 
 * @param unknown $form
 * @param unknown $form_state
 * @param unknown $form_id
 */

function simplenews_amazon_ses_form_alter(&$form, &$form_state, $form_id) {

  // Add validation, if sender's mail is verified by Amazon SES
  if ($form_id == 'simplenews_admin_category_form') {
    $form['simplenews_sender_information']['from_address']['#element_validate'] = array('verify_email_identity_amazon');
  }
  
  // Display domain records required in DKIM setting, 
  if ($form_id == 'amazon_domain_dkim_enable_form') {
    if (isset($form_state['values'])) {
      
      // When user clicks on Send Request button
      module_load_include('inc', 'simplenews_amazon_ses', 'includes/simplenews_amazon_ses.mail');
      if (($form_state['clicked_button']['#value']) == 'Send Request') {
        $selected_row = $form_state['values']['list_table'];
        $actionParameter['Identities'] = array(
            $form_state['complete form']['amazon_list_identities_update']['list_table']['#options'][$selected_row]['key']
        );
        
        // Call of amazon Query API action GetIdentityDkimAttributes
        $result = simplenews_amazon_ses_send_request('GetIdentityDkimAttributes', $actionParameter); // This request is throttled per second

        // Display the result in table returned by Amazon SES
        if (isset($result['status'])) {
          switch($result['status']) {
          	case KABOOTR_AMAZON_REQUEST_SUCCESS :
          	  $learn_dkim = l('Learn More about DKIM', 'http://docs.aws.amazon.com/ses/latest/DeveloperGuide/dkim.html');
          	  $form['div']['domain_dkim_token_table']['#options'] = $result['member'];
          	  
          	  // disable checkboxes in tableselect
          	  foreach ($result['member'] as $key => $value) {
          	    $form['div']['domain_dkim_token_table'][$key]['#disabled'] = TRUE;
          	  }
          	  $form['div']['domain_dkim_token_table']['#access'] = TRUE;
          	  $form['div']['domain_dkim_info']['#prefix'] = "<div id = domain_dkim_info <b>DKIM settings for your domain have been generated.</b> <br>
          	  The information below must be added to your domain's DNS records. How you update the DNS settings depends on who provides your DNS service;
          	  if your DNS service is provided by a domain name registrar, please contact that registrar to update your DNS records.{$learn_dkim} <br></br>
          	  <b>DKIM:</b> Waiting on sender verification... <br>
          	  <b>DKIM Verification Status:</b> {$result['DkimVerificationStatus']} <br></br>
          	  To enable DKIM signing for your domain, the records below must be entered in your DNS settings. AWS will automatically detect the presence of these records,
          	  and allow DKIM signing at that time. Note that verification of these settings may take up to 72 hours.<br>
          	  ";
          	  $form['div']['domain_dkim_info']['#suffix'] = '</div>';
          	  break;
          	  
            case KABOOTR_AMAZON_REQUEST_EXCEPTION :
              $message = t('Request to <b>!action</b> action of Amazon SES API call has failed,
                    please check your network connection or try after some time.', array(
                  '!action' => "GetIdentityDkimAttributes"
              ));
              drupal_set_message($message, 'error');
              break;
            
            case KABOOTR_AMAZON_REQUEST_FAILURE :
              $message = t('Request to <b>!action</b> action of Amazon SES API call has failed,
                    missing some parameter or Request is not valid.', array(
                  '!action' => "GetIdentityDkimAttributes"
              ));
              drupal_set_message($message, 'error');
              break;
          }
        }
      }
    }
  }
  
  // Alter test newsletter, mail should be send via amaozn ses
  if ($form_id == 'simplenews_node_tab_send_form') {
    module_load_include('inc', 'simplenews_amazon_ses', 'includes/simplenews_amazon_ses.admin');
    $form['#submit'] = array('simplenews_amazon_ses_node_tab_send_form_submit');
  }
  
  if ($form_id == 'simplenews_admin_newsletter_issues') {
    module_load_include('inc', 'simplenews_amazon_ses', 'includes/simplenews_amazon_ses.admin');
    $form['admin']['options']['operation']['#default_value'] = 'activate_amazon';
  }
 // require_once 'includes/classes/guzzle_request.php';
  //send_request_guzzle();
  
}

/**
 * TODO Validate, if send email is not verified by Amazon SES
 * @param  $element
 * @param  $form_state
 */
function verify_email_identity_amazon($element, &$form_state) {
  if (isset($element['#value'])) {
    $actionParameter['identity'] = $element['#value'];
    
    // Call the amazon Query API action GetIdentityVerificationAttributes
    $result = simplenews_amazon_ses_send_request('GetIdentityVerificationAttributes', $actionParameter, '');
    
    // Display the result in table returned by Amazon SES
    switch ($result['status']) {
    	case KABOOTR_IDENTITY_VERIFICATION_PENDING :
    	  form_error($element, t('!email address is in pending state, yet not verified by Amazon SES. \n so Please contact amazon SES or change the mail'
    	      , array('!email' => $element['#value'])));
    	      break;
    	case KABOOTR_IDENTITY_VERIFICATION_NOT :
    	  form_error($element, t('Please send request for verifying !email  address to Amazon SES, Or change the mail'
    	      , array('!email' => $element['#value'])));
    	  break;
    	case KABOOTR_AMAZON_REQUEST_EXCEPTION :
    	  form_error($element,t('Sending request to amazon is failed!, Please try again'));
    	      break;
    }
  }
}

/**
 * Implements hook_cron().
 */
//This function is currently commented, the functions run here will be tesed in form alter
function simplenews_amazon_ses_cron() {
  module_load_include('inc', 'simplenews_amazon_ses', 'includes/simplenews_amazon_ses.mail');
  simplenews_amazon_ses_mail_spool();
  //simplenews_amazon_ses_control_sending_mail();
  // Update sent status for newsletter admin panel.
}

/**
 * Implements hook_simplenews_issue_operations().
 */
function simplenews_amazon_ses_simplenews_issue_operations() {
  // @todo: future ideas: 'pause' => t('Pause sending'), 'resume' => t('Resume sending'), 'cancel' => t('Cancel sending'), 'publish' => t('Publish'), 'unpublish' => t('Unpublish'));
  $operations = array(
      'activate_amazon' => array(
          'label' => t('Send via Amazon'),
          'callback' => 'simplenews_amazon_ses_issue_send',
      ),
  );
  return $operations;
}