<?php 
/**
 * @file
 * Perform some additional action that will triggedred from simplenews contrib module
 */

/**
 * Implenment hook_update_kabootr_mail_sent defined by simplenews module.
 * Called after each mail sent to amazon ses and save the messageId and newsletter nid.
 */
function simplenews_extras_update_kabootr_mail_sent($newsletter_nid) {
	if (isset($_SESSION['amazon_ses']['message_id'])) {
		$data['message_id'] =  $_SESSION['amazon_ses']['message_id'];
		unset($_SESSION['amazon_ses']['message_id']);
		$data['nid'] = $newsletter_nid;
		kabootr_mail_sent_insert($data);
	}
}

/**
 * Save the messageId and newsletter into DB
 */
function kabootr_mail_sent_insert($data) {
	db_insert('kabootr_sent_mail')
	->fields(array(
			'message_id' => $data['message_id'],
			'nid' => $data['nid']
			)
		)
	->execute();	
}

/**
 * Load Kabootr mail sent by Message id
 */
function kabootr_mail_sent_load($message_id) {
	$kabootr_sent_mail = db_select('kabootr_sent_mail', 'ksm')
	->fields('ksm', array('nid'))
	->condition('message_id', $message_id, '=')
	->execute()
	->fetchAssoc();
	
	return $kabootr_sent_mail;
}

/**
 * Implements hook_simplenews_unsubscribe_user defined by simplenews module
 */
function simplenews_extras_simplenews_unsubscribe_user($subscriber, $newsletter) {
	$feedback_type = 'Unsubcribe';
	simplenews_amazon_ses_update_feedback($feedback_type, $subscriber->mail, '', $newsletter->tid);
}	